app/eventos/urls.py
from django.urls import path
from . import views as eventos

app_name = 'eventos'

urlpatterns = [
    path('', eventos.MeusEventos.as_view(), name='meus-eventos'),
    path('adicionar/evento', eventos.AddEvento.as_view(), name='add-evento'),
    path('deletar/evento/<pk>', eventos.DeletarEvento.as_view(), name='deletar-evento'),
    path('editar/evento/<pk>', eventos.EditarEvento.as_view(), name='editar-evento'),
    path('detalhes/evento/<pk>', eventos.DetalhesEvento.as_view(), name='detalhes-evento'),
    path('eventos/disponiveis', eventos.EventosDisponiveis.as_view(), name='eventos-disponiveis'),
    path('adicionar/minicurso', eventos.AddMinicurso.as_view(), name='add-minicurso'),
    path('adicionar/palestra', eventos.AddPalestra.as_view(), name='add-palestra'),
    path('inscrever/minicurso/<pk>', eventos.InscreverMinicurso.as_view(), name='inscrever-minicurso'),
    path('inscrever/palestra/<pk>', eventos.InscreverPalestra.as_view(), name='inscrever-palestra'),
    path('lista/minicurso/<pk>', eventos.GerarListaMinicurso.as_view(), name='gerar-lista-m'),
    path('lista/palestra/<pk>', eventos.GerarListaPalestra.as_view(), name='gerar-lista-p'),
    path('adicionar/palestrante', eventos.AddPalestrante.as_view(), name='add-palestrante'),
]

hub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.core.urls'), name='core'),
    path('', include('app.eventos.urls'), name='eventos'),
]

app/eventos/models.py
from django.db import models
from app.core.models import UUIDUser, CreateUpdateModel

class Palestra(CreateUpdateModel):
    evento = models.ForeignKey('Evento', on_delete=models.CASCADE, related_name='eventos', verbose_name='evento')
    nome = models.CharField(max_length=255, verbose_name='nome da palestra')
    palestrante = models.ForeignKey('Palestrante', on_delete=models.CASCADE, related_name='palestrante', verbose_name='palestrante')
    inscritos = models.ManyToManyField(UUIDUser, related_name='inscritos', verbose_name='inscritos', blank=True)
    duracao = models.TimeField(verbose_name='duração')
    data = models.DateField(verbose_name='data da atividade')
    horario = models.TimeField(verbose_name='hora da atividade')

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'palestra'
        verbose_name_plural = 'palestras'

class MiniCurso(CreateUpdateModel):
    evento = models.ForeignKey('Evento', on_delete=models.CASCADE, related_name='evento', verbose_name='evento')
    nome = models.CharField(max_length=255, verbose_name='nome do minicurso')
    palestrante = models.ForeignKey('Palestrante', on_delete=models.CASCADE, related_name='palestrantes', verbose_name='palestrante')
    inscritos = models.ManyToManyField(UUIDUser, related_name='inscrito', verbose_name='inscritos', blank=True)
    duracao = models.TimeField(verbose_name='duração')
    data = models.DateField(verbose_name='data da atividade')
    horario = models.TimeField(verbose_name='hora da atividade')

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'minicurso'
        verbose_name_plural = 'minicursos'

class Evento(CreateUpdateModel):
    dono = models.ForeignKey(UUIDUser, on_delete=models.CASCADE, related_name='users', verbose_name='dono do evento')
    nome = models.CharField(max_length=255, verbose_name='nome do evento')

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name_plural = 'eventos'
        verbose_name = 'evento'

class Palestrante(CreateUpdateModel):
    nome = models.CharField(max_length=255, verbose_name='nome do palestrante')

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'palestrante'
        verbose_name_plural = 'palestrantes'

app/eventos/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, ListView, DeleteView, UpdateView, View, DetailView
from django.urls import reverse_lazy
from .models import *

class MeusEventos(ListView):
    model = Evento
    template_name = 'eventos/meus-eventos.html'

    def get_context_data(self, **kwargs):
        kwargs['eventos'] = Evento.objects.filter(dono = self.request.user)
        return super(MeusEventos, self).get_context_data(**kwargs)

class EventosDisponiveis(ListView):
    model = Evento
    template_name = 'eventos/eventos-disponiveis.html'

    def get_context_data(self, **kwargs):
        kwargs['eventos'] = Evento.objects.all().exclude(dono = self.request.user)
        return super(EventosDisponiveis, self).get_context_data(**kwargs)

class AddEvento(CreateView):
    template_name = 'eventos/add-evento.html'
    model = Evento
    fields = ['dono', 'nome']
    success_url = reverse_lazy('eventos:meus-eventos')

class EditarEvento(UpdateView):
    model = Evento
    fields = ['nome']
    template_name = 'eventos/editar-evento.html'
    success_url = reverse_lazy('eventos:meus-eventos')

class DetalhesEvento(DetailView):
    model = Evento
    template_name = 'eventos/detalhes-evento.html'

    def get_context_data(self, **kwargs):
        kwargs['minicursos'] = MiniCurso.objects.filter(evento = self.object)
        kwargs['palestras'] = Palestra.objects.filter(evento = self.object)
        return super(DetalhesEvento, self).get_context_data(**kwargs)

class DeletarEvento(DeleteView):
    model = Evento
    success_url = reverse_lazy('eventos:meus-eventos')

class AddMinicurso(CreateView):
    model = MiniCurso
    fields = ['evento', 'nome', 'palestrante', 'duracao', 'data', 'horario']
    success_url = reverse_lazy('eventos:meus-eventos')
    template_name = 'eventos/add-minicurso.html'

class AddPalestra(CreateView):
    model = Palestra
    fields = ['evento', 'nome', 'palestrante', 'duracao', 'data', 'horario']
    success_url = reverse_lazy('eventos:meus-eventos')
    template_name = 'eventos/add-minicurso.html'

class InscreverMinicurso(View):
    def get(self, request, pk):
        minicurso = MiniCurso.objects.filter(id = pk).first()
        minicursos = MiniCurso.objects.filter(evento = minicurso.evento)
        aux = 0
        for atividade in minicursos:
            if self.request.user in atividade.inscritos.all():
                aux += 1
        if aux != 2:
            minicurso.inscritos.add(self.request.user)
            return redirect('eventos:meus-eventos')
        else:
            eventos = Evento.objects.filter(dono = self.request.user)
            return render(request, 'eventos/meus-eventos.html', {'mensagem': 'Você já está inscrito em 2 minicursos', 'eventos': eventos})

class InscreverPalestra(View):
    def get(self, request, pk):
        palestra = Palestra.objects.filter(id = pk).first()
        palestra.inscritos.add(self.request.user)
        return redirect('eventos:meus-eventos')

class GerarListaMinicurso(DetailView):
    model = MiniCurso
    template_name = 'eventos/lista.html'

class GerarListaPalestra(DetailView):
    model = Palestra
    template_name = 'eventos/lista.html'

class AddPalestrante(CreateView):
    model = Palestrante
    fields = ['nome']
    success_url = reverse_lazy('eventos:meus-eventos')
    template_name = 'eventos/add-palestrante.html'

templates/eventos/add-evento.html
{% extends '../base.html' %}

{% block content %}

<!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Eventos
      </h1>
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">Adicionar Evento</h3>
        </div>
        <div class="box-body">
          <form method="post">
              {% csrf_token %}
              <div class="form-group">
                  <label for="dono">Dono do Evento</label>
                  <select class="form-control" name="dono" id="dono">
                      <option value="{{ request.user.pk }}">{{ request.user.first_name }}</option>
                  </select>
              </div>
              <div class="form-group">
                  <label for="nome">Nome do Evento</label>
                  <input type="text" id="nome" name="nome" required class="form-control">
              </div>
              <input type="submit" value="Criar" class="btn btn-success">
          </form>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->

    </section>
    <!-- /.content -->

{% endblock %}

templates/eventos/add-minicurso.html
{% extends '../base.html' %}

{% block content %}

<!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Eventos
      </h1>
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">Adicionar Minicurso/Palestra</h3>
        </div>
        <div class="box-body">
          <form method="post">
              {% csrf_token %}
              {{ form.as_p }}
              <input type="submit" value="Adicionar" class="btn btn-success">
          </form>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->

    </section>
    <!-- /.content -->

{% endblock %}

templates/eventos/add-palestrante.html
{% extends '../base.html' %}

{% block content %}

<!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Palestrantes
      </h1>
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">Adicionar Palestrante</h3>
        </div>
        <div class="box-body">
          <form method="post">
              {% csrf_token %}
              <div class="form-group">
                  <label for="nome">Nome do Palestrante</label>
                  <input type="text" id="nome" name="nome" required class="form-control">
              </div>
              <input type="submit" value="Adicionar" class="btn btn-success">
          </form>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->

    </section>
    <!-- /.content -->

{% endblock %}

templates/eventos/detalhes-evento.html
{% extends '../base.html' %}

{% block content %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div style="float: right;">
          <a class="btn btn-success" href="{% url 'eventos:add-minicurso' %}">Adicionar Minicurso</a>
          <a class="btn btn-success" href="{% url 'eventos:add-palestra' %}">Adicionar Palestra</a>
      </div>
      <h1>
        Eventos
      </h1>
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">Detalhes do Evento ({{ object.nome }})</h3>
        </div>
        <div class="box-body">
          <div style="text-align: center;">
              <h3>Minicursos</h3>
          </div>
          {% if minicursos|length != 0 %}
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Palestrante</th>
                  <th scope="col">Nome</th>
                  <th scope="col">Data</th>
                  <th scope="col">Horário</th>
                  <th scope="col">Duração</th>
                  <th scope="col">Ações</th>
                </tr>
              </thead>
              <tbody>
              {% for minicurso in minicursos %}
                <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                  <td>{{ minicurso.palestrante }}</td>
                  <td>{{ minicurso.nome }}</td>
                  <td>{{ minicurso.data }}</td>
                  <td>{{ minicurso.horario }}</td>
                  <td>{{ minicurso.duracao }}</td>
                  <td><a href="{% url 'eventos:inscrever-minicurso' minicurso.pk %}" title="Inscrever-se"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                      <a href="{% url 'eventos:gerar-lista-m' minicurso.pk %}" target="_blank" title="Gerar Lista de Inscritos"><i class="fa fa-list" aria-hidden="true"></i></a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          {% else %}
            <div style="text-align: center;">
                <h3>Nenhum minicurso cadastrado</h3>
            </div>
          {% endif %}

          <div style="text-align: center;">
              <h3>Palestras</h3>
          </div>
          {% if palestras|length != 0 %}
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Palestrante</th>
                  <th scope="col">Nome</th>
                  <th scope="col">Data</th>
                  <th scope="col">Horário</th>
                  <th scope="col">Duração</th>
                  <th scope="col">Ações</th>
                </tr>
              </thead>
              <tbody>
              {% for palestra in palestras %}
                <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                  <td>{{ palestra.palestrante }}</td>
                  <td>{{ palestra.nome }}</td>
                  <td>{{ palestra.data }}</td>
                  <td>{{ palestra.horario }}</td>
                  <td>{{ palestra.duracao }}</td>
                  <td><a href="{% url 'eventos:inscrever-palestra' palestra.pk %}" title="Inscrever-se"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                      <a href="{% url 'eventos:gerar-lista-p' palestra.pk %}" target="_blank" title="Gerar Lista de Inscritos"><i class="fa fa-list" aria-hidden="true"></i></a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          {% else %}
            <div style="text-align: center;">
                <h3>Nenhuma palestra encontrada</h3>
            </div>
          {% endif %}
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->

    </section>
    <!-- /.content -->
{% endblock %}

templates/eventos/editar-evento.html
{% extends '../base.html' %}

{% block content %}

<!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Eventos
      </h1>
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">Editar Evento</h3>
        </div>
        <div class="box-body">
          <form method="post">
              {% csrf_token %}
              <div class="form-group">
                  <label for="nome">Nome do Evento</label>
                  <input type="text" id="nome" name="nome" required class="form-control" value="{{ object.nome }}">
              </div>
              <input type="submit" value="Editar" class="btn btn-success">
          </form>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->

    </section>
    <!-- /.content -->

{% endblock %}

templates/eventos/eventos-disponiveis.html
{% extends '../base.html' %}

{% block content %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Eventos
      </h1>
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">Eventos Disponíveis</h3>
        </div>
        <div class="box-body">
          {% if eventos|length != 0 %}
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Dono do Evento</th>
                  <th scope="col">Nome</th>
                  <th scope="col">Data da Criação</th>
                  <th scope="col">Ações</th>
                </tr>
              </thead>
              <tbody>
              {% for evento in eventos %}
                <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                  <td>{{ evento.dono }}</td>
                  <td>{{ evento.nome }}</td>
                  <td>{{ evento.created_at }}</td>
                  <td></td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          {% else %}
            <div style="text-align: center;">
                <h3>Nenhum evento disponível no momento</h3>
            </div>
          {% endif %}
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->

    </section>
    <!-- /.content -->
{% endblock %}

templates/eventos/lista.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Sistema de Eventos | AdminLTE</title>
  <!-- Favicon -->
  <link rel="shortcut icon" href="/static/bower_components/Ionicons/email_open.ico" />
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="/static/bower_components/bootstrap/dist/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/static/bower_components/font-awesome/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="/static/bower_components/Ionicons/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/static/dist/css/AdminLTE.min.css">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="/static/dist/css/skins/_all-skins.min.css">
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body>

<h3 style="text-align: center;">Lista de Inscritos</h3>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nome</th>
      <th scope="col">E-mail</th>
      <th scope="col">CPF</th>
      <th scope="col">Telefone</th>
    </tr>
  </thead>
  <tbody>
  {% for inscrito in object.inscritos.all %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ inscrito.first_name }} {{ inscrito.last_name }}</td>
      <td>{{ inscrito.email }}</td>
      <td>{{ inscrito.cpf }}</td>
      <td>{{ inscrito.telefone }}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>

<!-- jQuery 3 -->
<script src="/static/bower_components/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap 3.3.7 -->
<script src="/static/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- Slimscroll -->
<script src="/static/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
<!-- FastClick -->
<script src="/static/bower_components/fastclick/lib/fastclick.js"></script>
<!-- AdminLTE App -->
<script src="/static/dist/js/adminlte.min.js"></script>
<!-- iCheck -->
<script src="/static/plugins/iCheck/icheck.min.js"></script>
<!-- Page Script -->
<script>
  $(function () {
    //Enable iCheck plugin for checkboxes
    //iCheck for checkbox and radio inputs
    $('.mailbox-messages input[type="checkbox"]').iCheck({
      checkboxClass: 'icheckbox_flat-blue',
      radioClass: 'iradio_flat-blue'
    });

    //Enable check and uncheck all functionality
    $(".checkbox-toggle").click(function () {
      var clicks = $(this).data('clicks');
      if (clicks) {
        //Uncheck all checkboxes
        $(".mailbox-messages input[type='checkbox']").iCheck("uncheck");
        $(".fa", this).removeClass("fa-check-square-o").addClass('fa-square-o');
      } else {
        //Check all checkboxes
        $(".mailbox-messages input[type='checkbox']").iCheck("check");
        $(".fa", this).removeClass("fa-square-o").addClass('fa-check-square-o');
      }
      $(this).data("clicks", !clicks);
    });

    //Handle starring for glyphicon and font awesome
    $(".mailbox-star").click(function (e) {
      e.preventDefault();
      //detect type
      var $this = $(this).find("a > i");
      var glyph = $this.hasClass("glyphicon");
      var fa = $this.hasClass("fa");

      //Switch states
      if (glyph) {
        $this.toggleClass("glyphicon-star");
        $this.toggleClass("glyphicon-star-empty");
      }

      if (fa) {
        $this.toggleClass("fa-star");
        $this.toggleClass("fa-star-o");
      }
    });
  });
</script>
<!-- AdminLTE for demo purposes -->
<script src="/static/dist/js/demo.js"></script>
</body>
</html>

templates/eventos/meus-eventos.html
{% extends '../base.html' %}

{% block content %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div style="float: right;">
          <a class="btn btn-success" href="{% url 'eventos:add-evento' %}">Criar Novo Evento</a>
          <a class="btn btn-success" href="{% url 'eventos:add-palestrante' %}">Adicionar Palestrante</a>
      </div>
      <h1>
        Eventos
      </h1>
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">Meus Eventos</h3>
        </div>
        {% if mensagem %}
            <div class="alert alert-danger" role="alert">
                {{ mensagem }}
            </div>
        {% endif %}
        <div class="box-body">
          {% if eventos|length != 0 %}
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Nome</th>
                  <th scope="col">Data da Criação</th>
                  <th scope="col">Ações</th>
                </tr>
              </thead>
              <tbody>
              {% for evento in eventos %}
                <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                  <td>{{ evento.nome }}</td>
                  <td>{{ evento.created_at }}</td>
                  <td><a href="{% url 'eventos:detalhes-evento' evento.pk %}" title="Visualizar"><i class="fa fa-eye" aria-hidden="true"></i></a>
                      <form method="post" action="{% url 'eventos:deletar-evento' evento.pk %}">
                      {% csrf_token %}
                      <input type="submit" title="Excluir" value="Excluir">
                      </form>
                      <a href="{% url 'eventos:editar-evento' evento.pk %}" title="Editar"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          {% else %}
            <div style="text-align: center;">
                <h3>Nenhum evento encontrado</h3>
            </div>
          {% endif %}
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->

    </section>
    <!-- /.content -->
{% endblock %}