app/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views as core

app_name = 'core'

urlpatterns = [
	path('login/', auth_views.LoginView.as_view(template_name='core/login.html'), name='login'),
	path('logout/', auth_views.LogoutView.as_view(), name='logout'),
	path('cadastro/', core.UserCreateView.as_view(), name='cadastro'),
]

app/eventos/urls.py
from django.urls import path
from . import views as eventos

app_name = 'eventos'

urlpatterns = [
    path('', eventos.MeusEventos.as_view(), name='meus-eventos'),
    path('adicionar/evento', eventos.AddEvento.as_view(), name='add-evento'),
    path('deletar/evento/<pk>', eventos.DeletarEvento.as_view(), name='deletar-evento'),
    path('editar/evento/<pk>', eventos.EditarEvento.as_view(), name='editar-evento'),
    path('detalhes/evento/<pk>', eventos.DetalhesEvento.as_view(), name='detalhes-evento'),
    path('eventos/disponiveis', eventos.EventosDisponiveis.as_view(), name='eventos-disponiveis'),
    path('adicionar/minicurso', eventos.AddMinicurso.as_view(), name='add-minicurso'),
    path('adicionar/palestra', eventos.AddPalestra.as_view(), name='add-palestra'),
    path('inscrever/minicurso/<pk>', eventos.InscreverMinicurso.as_view(), name='inscrever-minicurso'),
    path('inscrever/palestra/<pk>', eventos.InscreverPalestra.as_view(), name='inscrever-palestra'),
    path('lista/minicurso/<pk>', eventos.GerarListaMinicurso.as_view(), name='gerar-lista-m'),
    path('lista/palestra/<pk>', eventos.GerarListaPalestra.as_view(), name='gerar-lista-p'),
    path('adicionar/palestrante', eventos.AddPalestrante.as_view(), name='add-palestrante'),
]

hub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.core.urls'), name='core'),
    path('', include('app.eventos.urls'), name='eventos'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Sistema de Eventos | AdminLTE</title>
  <!-- Favicon -->
  <link rel="shortcut icon" href="/static/bower_components/Ionicons/email_open.ico" />
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="/static/bower_components/bootstrap/dist/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/static/bower_components/font-awesome/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="/static/bower_components/Ionicons/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/static/dist/css/AdminLTE.min.css">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="/static/dist/css/skins/_all-skins.min.css">
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  <header class="main-header">
    <!-- Logo -->
    <a href="/" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>A</b>Mail</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Atom</b>Mail</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="" class="dropdown-toggle" data-toggle="dropdown">
              <img src="/static/dist/img/profile.png" class="user-image" alt="User Image">
              <span class="hidden-xs">{{request.user.first_name}} {{request.user.last_name}}</span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <img src="/static/dist/img/profile.png" class="img-circle" alt="User Image">

                <p>
                  {{request.user.first_name}} {{request.user.last_name}}
                  <small>Membro desde {{ request.user.date_joined|date:"d/M/Y" }}</small>
                </p>
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-right">
                  <a href="{% url 'core:logout' %}" class="btn btn-danger btn-flat">Sair</a>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="{% static 'dist/img/profile.png' %}" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>{{request.user.first_name}} {{request.user.last_name}}</p>
          <h6><i class="fa fa-circle text-success"></i> Online</h6>
        </div>
      </div>
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">BARRA DE NAVEGAÇÃO</li>
        <li class="treeview active">
          <a href="mailbox.html">
            <span>Eventos</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{% url 'eventos:meus-eventos' %}">Meus Eventos</a></li>
            <li>
              <a href="{% url 'eventos:eventos-disponiveis' %}">Disponíveis</a>
            </li>
          </ul>
        </li>
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    {% block content %}
    {% endblock %}
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Versão</b> 2.4.0
    </div>
    <strong>Copyright &copy; 2018 - AtomMail - Template: <a href="https://adminlte.io">Almsaeed Studio</a>.</strong> Todos os direitos reservados.
  </footer>
<!-- ./wrapper -->

<!-- jQuery 3 -->
<script src="/static/bower_components/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap 3.3.7 -->
<script src="/static/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- Slimscroll -->
<script src="/static/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
<!-- FastClick -->
<script src="/static/bower_components/fastclick/lib/fastclick.js"></script>
<!-- AdminLTE App -->
<script src="/static/dist/js/adminlte.min.js"></script>
<!-- iCheck -->
<script src="/static/plugins/iCheck/icheck.min.js"></script>
<!-- Page Script -->
<script>
  $(function () {
    //Enable iCheck plugin for checkboxes
    //iCheck for checkbox and radio inputs
    $('.mailbox-messages input[type="checkbox"]').iCheck({
      checkboxClass: 'icheckbox_flat-blue',
      radioClass: 'iradio_flat-blue'
    });

    //Enable check and uncheck all functionality
    $(".checkbox-toggle").click(function () {
      var clicks = $(this).data('clicks');
      if (clicks) {
        //Uncheck all checkboxes
        $(".mailbox-messages input[type='checkbox']").iCheck("uncheck");
        $(".fa", this).removeClass("fa-check-square-o").addClass('fa-square-o');
      } else {
        //Check all checkboxes
        $(".mailbox-messages input[type='checkbox']").iCheck("check");
        $(".fa", this).removeClass("fa-square-o").addClass('fa-check-square-o');
      }
      $(this).data("clicks", !clicks);
    });

    //Handle starring for glyphicon and font awesome
    $(".mailbox-star").click(function (e) {
      e.preventDefault();
      //detect type
      var $this = $(this).find("a > i");
      var glyph = $this.hasClass("glyphicon");
      var fa = $this.hasClass("fa");

      //Switch states
      if (glyph) {
        $this.toggleClass("glyphicon-star");
        $this.toggleClass("glyphicon-star-empty");
      }

      if (fa) {
        $this.toggleClass("fa-star");
        $this.toggleClass("fa-star-o");
      }
    });
  });
</script>
<!-- AdminLTE for demo purposes -->
<script src="/static/dist/js/demo.js"></script>
</body>
</html>